config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :articles do
    resources :comments
  end

  root 'welcome#index'
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
    length: { minimum: 5 }
  validates :text, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :commenter, presence: true;
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: "ole", password: "passord", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
      if @article.save
        redirect_to @article
      else
        render 'new'
      end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "ole", password: "passord", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
  	@article = Article.find(params[:article_id])
  	@comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
	<% if @article.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@article.errors.count, "reason") %> that the article couldn't be saved:
			</h2>
			<ul>
				<% @article.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/articles/edit.html.erb
<h1>Endre blogginnlegg</h1>

<%= render 'form' %>

<%= link_to 'Tilbake', articles_path %>

app/views/articles/index.html.erb
<h1>List of articles</h1>
<%= link_to 'New article', new_article_path %>
<p>
<table border="1">
  <tr>
    <th>Title</th>
    <th>Text</th>
	<th colspan="3"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Remove', article, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h1>Article # <%= @article.id %></h1>
<p>
	<h3>Title:</h3>
	<%= @article.title %>
</p>
<p>
	<h3>Text:</h3>
	<%= @article.text %>
</p>

<!-- <% i = - @article.comments.count + 1 %> -->
<% if @article.comments.count > 0 %>
	<h2> - Comments:</h2>
	<table>
			<%= render @article.comments, :i => i %>
	</table>
<% else %>
	<h2> - There is no comments</h2>
<% end %>

<h2> - Add a comment:</h2>



	<% if @article.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@article.errors.count, "reason") %> that the comment couldn't be saved:
			</h2>
			<ul>
				<% @article.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>




<%= form_for ([@article, @article.comments.build]) do |f| %>
	<p>
		<%= f.label :commenter %><br>
		<%= f.text_field :commenter %>
	</p>
	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

<%= link_to 'Edit', edit_article_path(@article) %><br>
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<tr>
<!--	<th rowspan="2"> # <%= @article.comments.count + i %></th> -->
	<th>Commenter:</th>
	<td><%= comment.commenter %></td>
	<td rowspan="2" style="align:middle"> <%= link_to 'Remove Comment', [comment.article, comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
<!--	<td><%= i %></td> -->
</tr>
<tr>
	<th>Comment:</th>
	<td><%= comment.body %></td>
</tr>
<tr>
	<td></td>
</tr>

app/views/comments/_form.html.erb
<p>Tull og tøys</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestProg</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blogg', controller: 'articles' %>